### ISSUE TITLE
ubuntu 16.04 build rippled failed

### ISSUE THREAD

**Issue by boy-good** [ripple/rippled#3029]
canning dependencies of target xrpl_core
[  4%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/core/core.unity.cpp.o
[  5%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_hash_unity.cpp.o
[  6%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_insight_unity.cpp.o
[  7%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_net_unity.cpp.o
[  7%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_utility_unity.cpp.o
[  8%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/basics1.cpp.o
[  9%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/json.cpp.o
[ 10%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o
In file included from /home/xrp/rippled/src/ripple/unity/protocol.cpp:25:0:
/home/xrp/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:162:77: error: ‘constexpr ripple::RPC::detail::ErrorInfoArray<M> ripple::RPC::detail::sortErrorInfos(const ripple::RPC::ErrorInfo (&)[N]) [with int M = 75; int N = 55]’ called in a constant expression
 constexpr auto sortedErrorInfos {sortErrorInfos<rpcLAST>(unorderedErrorInfos)};
                                                                             ^
/home/xrp/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116:1: note: ‘constexpr ripple::RPC::detail::ErrorInfoArray<M> ripple::RPC::detail::sortErrorInfos(const ripple::RPC::ErrorInfo (&)[N]) [with int M = 75; int N = 55]’ is not usable as a constexpr function because:
 sortErrorInfos (ErrorInfo const (&unordered)[N]) -> ErrorInfoArray<M>
 ^
/home/xrp/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116:1: sorry, unimplemented: unexpected AST of kind loop_expr
/home/xrp/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116: confused by earlier errors, bailing out
CMakeFiles/xrpl_core.dir/build.make:153: recipe for target 'CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o' failed
make[2]: *** [CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o] Error 1
CMakeFiles/Makefile2:304: recipe for target 'CMakeFiles/xrpl_core.dir/all' failed
make[1]: *** [CMakeFiles/xrpl_core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by seelabs** [comment]
Thank you for this report. We build rippled with newer versions of gcc, and it appears gcc 5.3 doesn't handle some of our new uses of `constexpr`. Upgrading gcc to at least gcc 7 should fix this issue.

**Comment by mmo2112** [comment]
I have same issue, 16.04 and gcc 7.4.0, trying to download sqlite but failed:
```
 --- LOG BEGIN ---
 Protocol "https" not supported or disabled in libcurl
Closing connection -1
 --- LOG END ---
 error: downloading 'https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip' failed
 status_code: 1
 status_string: "Unsupported protocol"
 log:
 --- LOG BEGIN ---
 Protocol "https" not supported or disabled in libcurl
Closing connection -1
 --- LOG END ---

CMakeFiles/sqlite3.dir/build.make:91: recipe for target '../.nih_c/unix_makefiles/GNU_7.4.0/Debug/src/sqlite3-stamp/sqlite3-download' failed
make[2]: *** [../.nih_c/unix_makefiles/GNU_7.4.0/Debug/src/sqlite3-stamp/sqlite3-download] Error 1
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/sqlite3.dir/all' failed
make[1]: *** [CMakeFiles/sqlite3.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by mellery451** [comment]
@mmo2112 that's not the same issue as originally reported here, which was about a compiler error. You are reporting an error downloading dependencies, possibly because your libcurl was not built with ssl support.

**Comment by mmo2112** [comment]
@mellery451, I have installed new curl, libtool-bin,... but still get this error. Should I create a new issue?

**Comment by dwjpeng** [comment]
I have the same question, bellow
[ 50%] Built target libarchive
Scanning dependencies of target xrpl_core
[ 51%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/core/core.unity.cpp.o
[ 52%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_hash_unity.cpp.o
[ 53%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_insight_unity.cpp.o
[ 54%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_net_unity.cpp.o
[ 54%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_utility_unity.cpp.o
[ 55%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/basics1.cpp.o
[ 56%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/json.cpp.o
[ 57%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o
In file included from /data/src/ripple/rippled/src/ripple/unity/protocol.cpp:25:0:
/data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:162:77: error: ‘constexpr ripple::RPC::detail::ErrorInfoArray<M> ripple::RPC::detail::sortErrorInfos(const ripple::RPC::ErrorInfo (&)[N]) [with int M = 75; int N = 55]’ called in a constant expression
 constexpr auto sortedErrorInfos {sortErrorInfos<rpcLAST>(unorderedErrorInfos)};
                                                                             ^
/data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116:1: note: ‘constexpr ripple::RPC::detail::ErrorInfoArray<M> ripple::RPC::detail::sortErrorInfos(const ripple::RPC::ErrorInfo (&)[N]) [with int M = 75; int N = 55]’ is not usable as a constexpr function because:
 sortErrorInfos (ErrorInfo const (&unordered)[N]) -> ErrorInfoArray<M>
 ^
/data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116:1: sorry, unimplemented: unexpected AST of kind loop_expr
/data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116: confused by earlier errors, bailing out
CMakeFiles/xrpl_core.dir/build.make:153: recipe for target 'CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o' failed
make[2]: *** [CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o] Error 1
CMakeFiles/Makefile2:304: recipe for target 'CMakeFiles/xrpl_core.dir/all' failed
make[1]: *** [CMakeFiles/xrpl_core.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dwjpeng** [comment]
> > @mmo2112 yes - please create a new issue, and I will see if I can reproduce it.
> 
> followed the steps of "[Build and Run rippled on Ubuntu"](https://xrpl.org/build-run-rippled-ubuntu.html#main_content_body), ubuntu 16.04 and gcc 7.4.0. I have the same question bellow.
> 
> [ 50%] Built target libarchive
> Scanning dependencies of target xrpl_core
> [ 51%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/core/core.unity.cpp.o
> [ 52%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_hash_unity.cpp.o
> [ 53%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_insight_unity.cpp.o
> [ 54%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_net_unity.cpp.o
> [ 54%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/beast/unity/beast_utility_unity.cpp.o
> [ 55%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/basics1.cpp.o
> [ 56%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/json.cpp.o
> [ 57%] Building CXX object CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o
> In file included from /data/src/ripple/rippled/src/ripple/unity/protocol.cpp:25:0:
> /data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:162:77: error: ‘constexpr ripple::RPC::detail::ErrorInfoArray ripple::RPC::detail::sortErrorInfos(const ripple::RPC::ErrorInfo (&)[N]) [with int M = 75; int N = 55]’ called in a constant expression
> constexpr auto sortedErrorInfos {sortErrorInfos(unorderedErrorInfos)};
> ^
> /data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116:1: note: ‘constexpr ripple::RPC::detail::ErrorInfoArray ripple::RPC::detail::sortErrorInfos(const ripple::RPC::ErrorInfo (&)[N]) [with int M = 75; int N = 55]’ is not usable as a constexpr function because:
> sortErrorInfos (ErrorInfo const (&unordered)[N]) -> ErrorInfoArray
> ^
> /data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116:1: sorry, unimplemented: unexpected AST of kind loop_expr
> /data/src/ripple/rippled/src/ripple/protocol/impl/ErrorCodes.cpp:116: confused by earlier errors, bailing out
> CMakeFiles/xrpl_core.dir/build.make:153: recipe for target 'CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o' failed
> make[2]: *** [CMakeFiles/xrpl_core.dir/src/ripple/unity/protocol.cpp.o] Error 1
> CMakeFiles/Makefile2:304: recipe for target 'CMakeFiles/xrpl_core.dir/all' failed
> make[1]: *** [CMakeFiles/xrpl_core.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2


I have fixed it.  this is a gcc problem. With two gcc versions in your ubuntu system, check the gcc version for update by "gcc --version", I can see "(Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609" ,that is not I want.  please link the gcc-7 to gcc in the path "/usr/bin".
steps bellow :
        1. cd /usr/bin                     # enter /usr/bin 
        2. sudo rm -r gcc             #remove old version gcc link
        3. sudo ln -sf gcc-7 gcc  #rebuild a new gcc4.7 soft links
        4. sudo rm -r g++             #same as gcc 
        5. sudo ln -sf g++-7 g++

**Comment by mmo2112** [comment]
@dwjpeng, sorry for late response because all of server are downed and I don't have server to test that... Thanks for your solution and have a  good day bro.
